version: 2.1

jobs:
  unit_test:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Set up Maven
          command: |
            curl -sL https://github.com/apache/maven/releases/download/maven-3.8.6/apache-maven-3.8.6-bin.tar.gz | tar -xz -C /usr/local
            export PATH=$PATH:/usr/local/apache-maven-3.8.6/bin
      - run:
          name: Run Unit Tests
          command: mvn test

  integration_test:
    docker:
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Setup Database
          command: |
            mysql -e "CREATE DATABASE test_db;"
      - run:
          name: Run Integration Tests
          command: mvn integration-test

  functional_test:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Run Selenium Tests
          command: mvn test -Dtest=com.mayab.quality.Integration.ServiceTest1

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: ./deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unit_test
      - integration_test:
          requires:
            - unit_test
      - functional_test:
          requires:
            - integration_test
      - deploy:
          requires:
            - functional_test
          filters:
            branches:
              only: main
